In [30]:
###############################################################################
# 1a: Create two random 0-d tensors x and y of any distribution.
# Create a TensorFlow object that returns x + y if x > y, and x - y otherwise.
# Hint: look up tf.cond()
# I do the first problem for you
###############################################################################

import tensorflow as tf
x = tf.random_uniform([])
y = tf.random_uniform([])

out = tf.cond(tf.less(x, y), lambda: tf.add(x, y), lambda: tf.subtract(x, y))

#####################################################################################
# out = tf.cond(tf.greater(x, y), lambda: tf.add(x, y), lambda: tf.subtract(x, y))  #
#####################################################################################


with tf.Session() as sess:
    print(sess.run(out))

0.814235
0.523714
0.0398927


In [37]:
###############################################################################
# 1b: Create two 0-d tensors x and y randomly selected from -1 and 1.
# Return x + y if x < y, x - y if x > y, 0 otherwise.
# Hint: Look up tf.case().
###############################################################################

x = tf.random_uniform([], -1, 1, dtype=tf.float32)
y = tf.random_uniform([], -1, 1, dtype=tf.float32)

def f1(): return tf.add(x,y)
def f2(): return tf.subtract(x, y)
def f3(): return tf.constant(0.)

##################################
# f1 = lambda: tf.add(x,y)
# f2 = lambda: tf.subtract(x,y)
# f3 = lambda: tf.constant(0.)
###################################

result = tf.case({tf.less(x,y) : f1, tf.greater(x, y) : f2}, default = f3, exclusive=True)

with tf.Session() as sess:
    print(sess.run(result))


-0.994302
-0.598815
-1.32509


In [38]:
###############################################################################
# 1c: Create the tensor x of the value [[0, -2, -1], [0, 1, 2]] 
# and y as a tensor of zeros with the same shape as x.
# Return a boolean tensor that yields Trues if x equals y element-wise.
# Hint: Look up tf.equal().
###############################################################################

x = tf.constant([[0, -2, -1],
                 [0, 1, 2]])
y = tf.zeros_like(x)

out = tf.equal(x, y)
with tf.Session() as sess:
    print(sess.run(out))


[[ True False False]
 [ True False False]]


In [60]:
###############################################################################
# 1d: Create the tensor x of value 
# [29.05088806,  27.61298943,  31.19073486,  29.35532951,
#  30.97266006,  26.67541885,  38.08450317,  20.74983215,
#  34.94445419,  34.45999146,  29.06485367,  36.01657104,
#  27.88236427,  20.56035233,  30.20379066,  29.51215172,
#  33.71149445,  28.59134293,  36.05556488,  28.66994858].
# Get the indices of elements in x whose values are greater than 30.
# Hint: Use tf.where().
# Then extract elements whose values are greater than 30.
# Hint: Use tf.gather().
###############################################################################
x = tf.constant([29.05088806,  27.61298943,  31.19073486,  29.35532951,
  30.97266006,  26.67541885,  38.08450317,  20.74983215,
  34.94445419,  34.45999146,  29.06485367,  36.01657104,
  27.88236427,  20.56035233,  30.20379066,  29.51215172,
  33.71149445,  28.59134293,  36.05556488,  28.66994858])

out1 = tf.where(x>30)
out2 = tf.gather(x, out1)
with tf.Session() as sess:
    print('tf.where result:\n', sess.run(out1))
    print('tf.gather result:\n',sess.run(out2))

tf.where result:
 [[ 2]
 [ 4]
 [ 6]
 [ 8]
 [ 9]
 [11]
 [14]
 [16]
 [18]]
tf.gather result:
 [[ 31.19073486]
 [ 30.97266006]
 [ 38.08450317]
 [ 34.94445419]
 [ 34.45999146]
 [ 36.01657104]
 [ 30.20379066]
 [ 33.71149445]
 [ 36.05556488]]


In [62]:
###############################################################################
# 1e: Create a diagnoal 2-d tensor of size 6 x 6 with the diagonal values of 1,
# 2, ..., 6
# Hint: Use tf.range() and tf.diag().
###############################################################################
x = tf.range(1, 7, 1)
out = tf.diag(x)
with tf.Session() as sess:
    print(sess.run(x))
    print(sess.run(out))

[1 2 3 4 5 6]
[[1 0 0 0 0 0]
 [0 2 0 0 0 0]
 [0 0 3 0 0 0]
 [0 0 0 4 0 0]
 [0 0 0 0 5 0]
 [0 0 0 0 0 6]]


In [65]:
###############################################################################
# 1f: Create a random 2-d tensor of size 10 x 10 from any distribution.
# Calculate its determinant.
# Hint: Look at tf.matrix_determinant().
###############################################################################
x = tf.random_normal([10,10], dtype=tf.float32)
out = tf.matrix_determinant(x)
with tf.Session() as sess:
    print('random normal matrix:\n', sess.run(x))
    print('matrix determinant:\n', sess.run(out))

random normal matrix:
 [[-1.5664016  -0.69449127  0.40231338  0.16469468  0.57276493  1.36004806
   1.24369204  0.23808007  2.37089729 -0.36080545]
 [-0.32272708 -0.13085271  1.1715101  -1.39082336  0.63230938 -1.20282567
   1.18561769  0.52183157 -0.03114838 -0.26905236]
 [-0.05777624  0.79496527 -0.55835694  0.49164858 -1.12662315 -0.42774639
  -0.70219034 -1.21515191 -0.47081864 -0.1437607 ]
 [ 1.17403984 -1.08039832  2.85253215  0.8951956  -1.96989977  2.8322165
  -0.4479551  -1.81451178  1.32456458  1.68375731]
 [-0.66591972 -0.39290351 -0.5278824  -1.01384604 -0.51343942  3.36856008
  -0.07531173 -0.74610305  0.10860763  0.37045258]
 [ 1.03124487  0.67596221 -0.55944514  0.63002819 -0.28316316 -0.52950919
  -0.67263353  1.98288333 -0.57647204  0.39759448]
 [ 1.77038527  1.23074138 -0.8933692  -0.84844428  0.35630095 -1.17121243
   0.3119995  -1.1921593  -1.3230617  -1.10906577]
 [ 1.04053664 -1.49891984  0.05324095  1.39991581  0.34909883  0.98274255
   0.32587832  1.00348079  0.

In [67]:
###############################################################################
# 1g: Create tensor x with value [5, 2, 3, 5, 10, 6, 2, 3, 4, 2, 1, 1, 0, 9].
# Return the unique elements in x
# Hint: use tf.unique(). Keep in mind that tf.unique() returns a tuple.
###############################################################################
x = tf.constant([5, 2, 3, 5, 10, 6, 2, 3, 4, 2, 1, 1, 0, 9])
y, index = tf.unique(x)
with tf.Session() as sess:
    print('x: \n',sess.run(x))
    print('unique elements: \n',sess.run(y))
    print('the index of each value of x in the unique output: \n', sess.run(index))

x: 
 [ 5  2  3  5 10  6  2  3  4  2  1  1  0  9]
unique elements: 
 [ 5  2  3 10  6  4  1  0  9]
the index of each value of x in the unique output: 
 [0 1 2 0 3 4 1 2 5 1 6 6 7 8]


In [81]:
###############################################################################
# 1h: Create two tensors x and y of shape 300 from any normal distribution,
# as long as they are from the same distribution.
# Use tf.less() and tf.select() to return:
# - The mean squared error of (x - y) if the average of all elements in (x - y)
#   is negative, or
# - The sum of absolute value of all elements in the tensor (x - y) otherwise.
# Hint: see the Huber loss function in the lecture slides 3.
###############################################################################
x = tf.random_normal([300], dtype=tf.float32)
y = tf.random_normal([300], dtype=tf.float32)

average = tf.reduce_mean(x-y)
condition = tf.less(average, 0)
op1 = tf.reduce_mean(tf.square(x-y))
op2 = tf.reduce_sum(tf.abs(x-y))
out = tf.cond(condition, lambda: op1, lambda: op2)

########################
out2 = tf.where(condition, op1, op2)
######################

with tf.Session() as sess:
    print(sess.run(out))

2.07544
