In [1]:
import tensorflow as tf

In [2]:
###############################################################################
# 1a: Create two random 0-d tensors x and y of any distribution.
# Create a TensorFlow object that returns x + y if x > y, and x - y otherwise.
# Hint: look up tf.cond()
###############################################################################
x = tf.random_normal([])
y = tf.random_normal([])
output = tf.cond(tf.greater(x, y), lambda: tf.add(x, y), lambda: tf.subtract(x, y))

with tf.Session() as sess:
    print(sess.run([x, y, output]))

[0.49730092, -0.6695627, -0.17226177]


In [3]:
###############################################################################
# 1b: Create two 0-d tensors x and y randomly selected from -1 and 1.
# Return x + y if x < y, x - y if x > y, 0 otherwise.
# Hint: Look up tf.case().
###############################################################################
x = tf.random_uniform([], -1, 1)
y = tf.random_uniform([], -1, 1)
output = tf.case({
    tf.greater(x, y): lambda: tf.subtract(x, y),
    tf.less(x, y): lambda: tf.add(x, y),
}, default=lambda: tf.constant(0.0), exclusive=True)

with tf.Session() as sess:
    print(sess.run([x, y, output]))

[-0.001718998, -0.46350598, 0.46178699]


In [4]:
###############################################################################
# 1c: Create the tensor x of the value [[0, -2, -1], [0, 1, 2]] 
# and y as a tensor of zeros with the same shape as x.
# Return a boolean tensor that yields Trues if x equals y element-wise.
# Hint: Look up tf.equal().
###############################################################################
x = tf.constant([[0, -2, -1], [0, 1, 2]])
y = tf.zeros_like(x)
output = tf.equal(x, y)

with tf.Session() as sess:
    print(sess.run([x, y, output]))

[array([[ 0, -2, -1],
       [ 0,  1,  2]], dtype=int32), array([[0, 0, 0],
       [0, 0, 0]], dtype=int32), array([[ True, False, False],
       [ True, False, False]], dtype=bool)]


In [5]:
###############################################################################
# 1d: Create the tensor x of value 
# [29.05088806,  27.61298943,  31.19073486,  29.35532951,
#  30.97266006,  26.67541885,  38.08450317,  20.74983215,
#  34.94445419,  34.45999146,  29.06485367,  36.01657104,
#  27.88236427,  20.56035233,  30.20379066,  29.51215172,
#  33.71149445,  28.59134293,  36.05556488,  28.66994858].
# Get the indices of elements in x whose values are greater than 30.
# Hint: Use tf.where().
# Then extract elements whose values are greater than 30.
# Hint: Use tf.gather().
###############################################################################
x = tf.constant(
    [ 29.05088806,  27.61298943,  31.19073486,  29.35532951,
      30.97266006,  26.67541885,  38.08450317,  20.74983215,
      34.94445419,  34.45999146,  29.06485367,  36.01657104,
      27.88236427,  20.56035233,  30.20379066,  29.51215172,
      33.71149445,  28.59134293,  36.05556488,  28.66994858])
indices = tf.where(tf.greater(x, 30))
output = tf.gather(x, indices)
with tf.Session() as sess:
    print(sess.run(output))

[[ 31.19073486]
 [ 30.97266006]
 [ 38.08450317]
 [ 34.94445419]
 [ 34.45999146]
 [ 36.01657104]
 [ 30.20379066]
 [ 33.71149445]
 [ 36.05556488]]


In [6]:
###############################################################################
# 1e: Create a diagnoal 2-d tensor of size 6 x 6 with the diagonal values of 1,
# 2, ..., 6
# Hint: Use tf.range() and tf.diag().
###############################################################################
values = tf.range(1, 7)
output = tf.diag(values)

with tf.Session() as sess:
    print(sess.run(output))

[[1 0 0 0 0 0]
 [0 2 0 0 0 0]
 [0 0 3 0 0 0]
 [0 0 0 4 0 0]
 [0 0 0 0 5 0]
 [0 0 0 0 0 6]]


In [7]:
###############################################################################
# 1f: Create a random 2-d tensor of size 10 x 10 from any distribution.
# Calculate its determinant.
# Hint: Look at tf.matrix_determinant().
###############################################################################
x = tf.random_normal([10, 10])
determiant = tf.matrix_determinant(x)
with tf.Session() as sess:
    print(sess.run(determiant))

-54.5403


In [8]:
###############################################################################
# 1g: Create tensor x with value [5, 2, 3, 5, 10, 6, 2, 3, 4, 2, 1, 1, 0, 9].
# Return the unique elements in x
# Hint: use tf.unique(). Keep in mind that tf.unique() returns a tuple.
###############################################################################
x = tf.constant([5, 2, 3, 5, 10, 6, 2, 3, 4, 2, 1, 1, 0, 9])
output = tf.unique(x)
with tf.Session() as sess:
    print(sess.run(output[0]))

[ 5  2  3 10  6  4  1  0  9]


In [21]:
###############################################################################
# 1h: Create two tensors x and y of shape 300 from any normal distribution,
# as long as they are from the same distribution.
# Use tf.less() and tf.where() to return:
# - The mean squared error of (x - y) if the average of all elements in (x - y)
#   is negative, or
# - The sum of absolute value of all elements in the tensor (x - y) otherwise.
# Hint: see the Huber loss function in the lecture slides 3.
###############################################################################
# x = tf.truncated_normal([2], mean=0.0, stddev=1, dtype=tf.float32, name='x')
# y = tf.truncated_normal([2], mean=0.0, stddev=1, dtype=tf.float32, name='y')
x = tf.Variable(tf.truncated_normal([2], mean=0.0, stddev=1, dtype=tf.float32, name='x'))
y = tf.Variable(tf.truncated_normal([2], mean=0.0, stddev=1, dtype=tf.float32, name='y'))

# x = tf.constant([ 3, 7])
# y = tf.constant([ 4, 5])

error = tf.subtract(x ,y)
mean = tf.reduce_mean(error)

condition = tf.less(mean, 0)
left = tf.reduce_mean(tf.square(error))
right = tf.reduce_sum(tf.abs(error))

output = tf.where(condition, left, right)
output2 = tf.cond(condition, lambda: left, lambda: right)

init = tf.global_variables_initializer()
with tf.Session() as sess:
    sess.run(init)
    print('x is:', sess.run(x))
    print('y is:', sess.run(y))
    print('error is :', sess.run(error))
    print('x - y is :', sess.run(x - y))
#     print('square is :', sess.run(tf.square(error)))
#     print('square_sum is:', sess.run(tf.reduce_sum(tf.square(error))))
#     print('abs is:', sess.run(tf.abs(error)))
#     print('condition is:', sess.run(condition))
#     print('left is: ', sess.run(left))
#     print('right is: ', sess.run(right))
    print(sess.run(output))
    print(sess.run(output2))

x is: [-0.17287591  0.70611757]
y is: [ 1.15783191 -0.46797895]
error is : [-1.33070779  1.17409658]
x - y is : [-1.33070779  1.17409658]
1.57464
1.57464


In [24]:
x = tf.constant([2,8])
y = tf.constant([5,3])
result = tf.cond(x[0] < y[0], lambda: tf.add(x, y), lambda: tf.subtract(y, x))
result2 = tf.where(x < y, tf.add(x, y), tf.subtract(y, x))
with tf.Session() as sess:
    print(sess.run(result))
    print(sess.run(result2))

[ 7 11]
[ 7 -5]


In [11]:
import tensorflow as tf
x = tf.random_uniform([])
y = tf.random_uniform([])

out = tf.cond(tf.less(x, y), lambda: tf.add(x, y), lambda: tf.subtract(x, y))
with tf.Session() as sess:
    print(sess.run([x, y, out]))

[0.090107679, 0.040316582, 0.049791098]


In [12]:
###############################################################################
# 1b: Create two 0-d tensors x and y randomly selected from -1 and 1.
# Return x + y if x < y, x - y if x > y, 0 otherwise.
# Hint: Look up tf.case().
###############################################################################

x = tf.random_uniform([], -1, 1, dtype=tf.float32)
y = tf.random_uniform([], -1, 1, dtype=tf.float32)


##################################
f1 = lambda: tf.add(x,y)
f2 = lambda: tf.subtract(x,y)
f3 = lambda: tf.constant(0.)
###################################
result = tf.case({tf.less(x,y) : f1, tf.greater(x, y) : f2}, default = f3, exclusive=True)

with tf.Session() as sess:
    print(sess.run(result))


-0.176333
