In [3]:
# Import tensorflow
import tensorflow as tf

In [4]:
sess = tf.Session()

In [17]:
logits_true = tf.nn.softmax([1.3, -4.5, 1.5, 3.0])
logits_gen = tf.nn.softmax([3.7, 3.5, -1.3, 3.7])
print(sess.run(logits_true))
print(sess.run(logits_gen))

print(sess.run(tf.log(0.35392359)))
print(sess.run(tf.log(1.29897490e-01) + 
               tf.log(1 - 0.35392359)))

[  1.29897490e-01   3.93271766e-04   1.58657163e-01   7.11052060e-01]
[ 0.35392359  0.2897681   0.00238472  0.35392359]
-1.03867
-2.47785


In [ ]:
# Constants, Sequences, and Random Values
# link: https://www.tensorflow.org/versions/r0.10/api_docs/python/constant_op/

In [13]:
x = tf.linspace(-3.0, 3.0, 32)
print(sess.run(x))
print(sess.run(tf.multinomial(tf.log([[10., 10., 10., 9., 1.],[10., 10., 1., 2., 5.]]), 5)))

[-3.         -2.80645156 -2.61290312 -2.41935492 -2.22580647 -2.03225803
 -1.83870971 -1.64516139 -1.45161295 -1.25806451 -1.06451619 -0.87096786
 -0.67741942 -0.48387098 -0.29032278 -0.09677434  0.0967741   0.29032254
  0.48387098  0.67741919  0.87096763  1.06451607  1.25806427  1.45161295
  1.64516115  1.83870935  2.03225803  2.22580624  2.41935444  2.61290312
  2.80645132  3.        ]
[[2 1 2 0 1]
 [1 0 1 3 0]]


In [17]:
print(sess.run(tf.multiply(2, 3, name=None)))

6


In [18]:
t_1 = ['apple', 'peach', 'banana']
print(sess.run(tf.zeros_like(t_1)) )

[b'' b'' b'']


In [22]:
import tensorflow as tf
my_const = tf.constant([1.0, 2.0], name="my_const")
with tf.Session() as sess:
    print(sess.graph.as_graph_def())

node {
  name: "LinSpace/start"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_FLOAT
        tensor_shape {
        }
        float_val: -3.0
      }
    }
  }
}
node {
  name: "LinSpace/stop"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_FLOAT
        tensor_shape {
        }
        float_val: 3.0
      }
    }
  }
}
node {
  name: "LinSpace/num"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_INT32
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_INT32
        tensor_shape {
        }
        int_val: 32
      }
    }
  }
}
node {
  name: "LinSpace"
  op: "LinSpace"
  input: "LinSpace/start"
  input: "LinSpace/stop"
  input: "LinSpace/num"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: 