### Sample

In [1]:
import tensorflow as tf
x = tf.random_uniform([])
y = tf.random_uniform([])
out = tf.cond(tf.less(x,y), lambda: tf.add(x,y), lambda: tf.subtract(x,y))

### Answer 1

In [2]:
import tensorflow as tf
x = tf.random_uniform([], minval=-1, maxval=1)
y = tf.random_uniform([], minval=-1, maxval=1)
fn1 = lambda: tf.add(x,y)
fn2 = lambda: tf.subtract(x,y)
fn3 = lambda: tf.constant(0.0)
out = tf.case([(tf.less(x,y), fn1), (tf.greater(x,y), fn2)], default=fn3)
with tf.Session() as sess:
    print(sess.run(out))

-1.33227


### Answer 2

In [36]:
import tensorflow as tf
x = tf.constant([[0, -2, -1], [0, 1, 2]])
y = tf.zeros_like(x)
out = tf.equal(x,y)
with tf.Session() as sess:
    print(sess.run(out))

[[ True False False]
 [ True False False]]


### Answer 3

In [41]:
import tensorflow as tf
x = tf.constant(
    [29.05088806,  27.61298943,  31.19073486,  29.35532951,
     30.97266006,  26.67541885,  38.08450317,  20.74983215,
     34.94445419,  34.45999146,  29.06485367,  36.01657104,
     27.88236427,  20.56035233,  30.20379066,  29.51215172,
     33.71149445,  28.59134293,  36.05556488,  28.66994858])
indices = tf.where(x>30)
out = tf.gather(x, indices)
with tf.Session() as sess:
    print(sess.run(out))

[[ 31.19073486]
 [ 30.97266006]
 [ 38.08450317]
 [ 34.94445419]
 [ 34.45999146]
 [ 36.01657104]
 [ 30.20379066]
 [ 33.71149445]
 [ 36.05556488]]


### Answer 4

In [42]:
import tensorflow as tf
x = tf.range(1, 7, 1)
out = tf.diag(x)
with tf.Session() as sess:
    print(sess.run(out))

[[1 0 0 0 0 0]
 [0 2 0 0 0 0]
 [0 0 3 0 0 0]
 [0 0 0 4 0 0]
 [0 0 0 0 5 0]
 [0 0 0 0 0 6]]


### Answer 5

In [44]:
import tensorflow as tf
x = tf.random_normal([10,10])
out = tf.matrix_determinant(x)
with tf.Session() as sess:
    print(sess.run(out))

-421.399


### Answer 6

In [45]:
import tensorflow as tf
x = tf.constant([5, 2, 3, 5, 10, 6, 2, 3, 4, 2, 1, 1, 0, 9])
out, idx = tf.unique(x)
with tf.Session() as sess:
    print(sess.run(out))

[ 5  2  3 10  6  4  1  0  9]


### Answer 7

In [5]:
import tensorflow as tf
x = tf.random_normal([300], mean=3, stddev=1)
y = tf.random_normal([300], mean=3, stddev=1)
average = tf.reduce_mean(x-y)
fn1 = lambda: tf.reduce_mean(tf.square(x-y))
fn2 = lambda: tf.reduce_sum(tf.abs(x-y))
out = tf.cond(tf.less(average, 0), fn1, fn2)
out1 = tf.where(tf.less(average, 0), tf.reduce_mean(tf.square(x-y)), tf.reduce_sum(tf.abs(x-y)))
with tf.Session() as sess:
    print(sess.run(out))
    print(sess.run(out1))

1.8628
349.867
